bashrc: Unset SSH_ASKPASS to avoid launching gnome-ssh-askpass.
Git tries to launch gnome-ssh-askpass when pushing and causes
the following warning:

	(gnome-ssh-askpass:29331): Gtk-WARNING **: cannot open display:
	error: unable to read askpass response from '/usr/libexec/openssh/gnome-ssh-askpass'

Command line password is just fine for me.